name: release pipeline
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: lalith-org/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: frontend-expense
      npm_install: false
      release_archive_file: "*.js package.json schema VERSION node_modules"
    secrets: inherit